In [2]:
import pandas as pd

In [3]:
expenses = pd.read_csv("../data/raw/jul_2026.csv")

In [4]:
print(expenses.shape)

(115, 12)

In [5]:
expenses.head()

,Account Details For:,My Account 019-027956-1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Statement as at:,31 Jul 2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Currency:,SGD - Singapore Dollar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Available Balance:,SGD 17084.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
expenses.info()

<class 'pandas.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Account Details For:     112 non-null    str
 1   My Account 019-027956-1  112 non-null    str
 2   Unnamed: 2               108 non-null    str
 3   Unnamed: 3               108 non-null    str
 4   Unnamed: 4               108 non-null    str
 5   Unnamed: 5               108 non-null    str
 6   Unnamed: 6               108 non-null    str
 7   Unnamed: 7               107 non-null    str
 8   Unnamed: 8               108 non-null    str
 9   Unnamed: 9               108 non-null    str
 10  Unnamed: 10              99 non-null     str
 11  Unnamed: 11              10 non-null     str
dtypes: str(12)
memory usage: 10.9 KB

In [7]:
expenses.describe()

,Account Details For:,My Account 019-027956-1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
count,112,112,108,108,108,108,108,107,108,108,99,10
unique,33,5,3,108,77,3,13,102,2,2,89,7
top,30 Jul 2026,31 Jul 2026,POS,Description,TRF TOP-UP TO PAYLAH! :,Point-of-Sale Transaction,4628-4500-4119-8533,OTHR PayNow Transfer,Settled,SGD,4,7.8
freq,8,108,70,1,28,70,70,5,107,107,3,3

In [8]:
Availble_balance = expenses.iloc[4,1]
print(Availble_balance)

SGD 17084.02

In [9]:
Ledger_balance = expenses.iloc[5,1]
print(Ledger_balance)

SGD 17136.32

In [10]:
header = expenses.iloc[7:].head(5)
print(header)

   Account Details For: My Account 019-027956-1      Unnamed: 2  \
7      Transaction Date              Value Date  Statement Code
8           30 Jul 2026             31 Jul 2026             POS
9           30 Jul 2026             31 Jul 2026             POS
10          30 Jul 2026             31 Jul 2026             ADV
11          30 Jul 2026             31 Jul 2026             ADV

                                           Unnamed: 3  \
7                                         Description
8   BAT BUS/MRT 896469166 SI SGP 25JUL 4628-4500-4...
9   BAT MISTER DONUT - NORTHPO SI SGP 27JUL 4628-4...
10  ICT Incoming PayNow Ref 7767267 From: JETHRO L...
11  ICT Incoming PayNow Ref 7763787 From: AIDEN JU...

                                 Unnamed: 4                      Unnamed: 5  \
7                        Supplementary Code  Supplementary Code Description
8   BAT BUS/MRT 896469166      SI SGP 25JUL       Point-of-Sale Transaction
9   BAT MISTER DONUT - NORTHPO SI SGP 27JUL       Point-of-Sale Transaction
10          ICT Incoming PayNow Ref 7767267                          Advice
11          ICT Incoming PayNow Ref 7763787                          Advice

                             Unnamed: 6            Unnamed: 7 Unnamed: 8  \
7                      Client Reference  Additional Reference     Status
8                   4628-4500-4119-8533       000002779772610    Settled
9                   4628-4500-4119-8533       000002777774581    Settled
10          From: JETHRO LEE CHONG TECK  OTHR PayNow Transfer    Settled
11  From: AIDEN JUSTIN TAN (CHEN YIJUN)  OTHR PayNow Transfer    Settled

   Unnamed: 9   Unnamed: 10    Unnamed: 11
7    Currency  Debit Amount  Credit Amount
8         SGD          3.36            NaN
9         SGD            14            NaN
10        SGD           NaN            8.8
11        SGD           NaN            7.8

In [11]:
expenses_data = pd.read_csv("../data/raw/jul_2026.csv", header = 8)
expenses_data.head()

,Transaction Date,Value Date,Statement Code,Description,Supplementary Code,Supplementary Code Description,Client Reference,Additional Reference,Status,Currency,Debit Amount,Credit Amount
0,30 Jul 2026,31 Jul 2026,POS,BAT BUS/MRT 896469166 SI SGP 25JUL 4628-4500-4...,BAT BUS/MRT 896469166 SI SGP 25JUL,Point-of-Sale Transaction,4628-4500-4119-8533,000002779772610,Settled,SGD,3.36,NaN
1,30 Jul 2026,31 Jul 2026,POS,BAT MISTER DONUT - NORTHPO SI SGP 27JUL 4628-4...,BAT MISTER DONUT - NORTHPO SI SGP 27JUL,Point-of-Sale Transaction,4628-4500-4119-8533,000002777774581,Settled,SGD,14.00,NaN
2,30 Jul 2026,31 Jul 2026,ADV,ICT Incoming PayNow Ref 7767267 From: JETHRO L...,ICT Incoming PayNow Ref 7767267,Advice,From: JETHRO LEE CHONG TECK,OTHR PayNow Transfer,Settled,SGD,NaN,8.8
3,30 Jul 2026,31 Jul 2026,ADV,ICT Incoming PayNow Ref 7763787 From: AIDEN JU...,ICT Incoming PayNow Ref 7763787,Advice,From: AIDEN JUSTIN TAN (CHEN YIJUN),OTHR PayNow Transfer,Settled,SGD,NaN,7.8
4,30 Jul 2026,31 Jul 2026,ADV,ICT Incoming PayNow Ref 7763365 From: TAN E-JA...,ICT Incoming PayNow Ref 7763365,Advice,From: TAN E-JAE,OTHR PayNow Transfer,Settled,SGD,NaN,7.8

In [1]:
import sys
sys.path.append("../src")

from etl import run_etl
from categorise import summarize_uncategorized

combined = run_etl()
summarize_uncategorized(combined)

                         Supplementary Code  count
0                                                5
1   BAT Grab* A-96649EMWWDUVAV Si SGP 04APR      2
2   BAT DBS VISA DEBIT CASHBACK JAN   26FEB      1
3   BAT SENTOSA EXPRESS Singapore SGP 24FEB      1
4   BAT TREASURE TOAST PTE LTD Si SGP 09FEB      1
5   BAT NET*SPECTRUM STORE     SI SGP 09FEB      1
6   BAT BBQ WHOLESALE CENTRE ( SI SGP 08FEB      1
7   BAT Grab* A-8UHE5GLWW63LAV Si SGP 03FEB      1
8   BAT Volleyball World. CLEE Am NLD 30MAR      1
9   BAT DBS VISA DEBIT CASHBACK FEB   24MAR      1
10  BAT SMP*OTTIE PANCAKES     Si SGP 16MAR      1
11  BAT SOUTH SIDE KEPPEL      Si SGP 12MAR      1
12  BAT TREASURE TOAST PTE LTD Si SGP 03MAR      1
13  BAT IAMSTILL Koggii Suntec Si SGP 24APR      1
14                      ICT SYFE WITHDRAWAL      1
15  BAT SMP*NG KUAN CHILI PAN  Si SGP 16APR      1
16  BAT GRB*Lola s Lorong Mamb Si SGP 15APR      1
17  BAT MUJI-BUGIS JUNCTION    SI SGP 14APR      1
18  BAT BUTA KIZOKU PTE. LTD.  SI SGP 13APR      1
19  BAT gotogate1123224537771 SG      07APR      1
20  BAT DBS VISA DEBIT CASHBACK APR   29MAY      1
21  BAT BOULDERHQ PTE  LTD     SI SGP 20MAY      1
22  BAT YHS VENDING MACHINE    Si SGP 12MAY      1
23  BAT YHS VENDING MACHINE    Si SGP 07MAY      1
24  BAT NEX FJ-POT MASTER CLAY SI SGP 06MAY      1
25  BAT YHS(SINGAPORE) Singapore SGP  29APR      1
26  BAT DBS VISA DEBIT CASHBACK MAY   26JUN      1
27  BAT KIMOJ BUGIS+ SINGAPORE SGP    25JUN      1
28  BAT TWYST AT NORTHPOINT CI Si SGP 22JUN      1
29  BAT YHS VENDING MACHINE    Si SGP 18JUN      1
30                          ICT WHDWS464316      1
31  BAT Grab* A-9EU4JRFGW7QSAV Si SGP 11JUN      1
32                        RTF 0016RF8926248      1
33  BAT KANGHODONG BAEKJEONG.. SI SGP 03JUN      1
34                        RTF 0016RF8735206      1
35                        RTF 0016RF8719777      1
36  BAT SAFRA Singapore SGP           01JUN      1
37                     ITT QA7LD2403MRF1469      1
38  BAT ORANGE DENTAL CLINIC P Si SGP 17JUL      1
39  BAT LENSKART NEX SINGAPORE SGP    17JUL      1
40  BAT CHIRASHIZUSHI SHOU_THO SI SGP 08JUL      1
41  BAT SMP*Sunrise Chicken Ri Si SGP 06JUL      1
42  BAT BEN'S COOKIES-STC      SI SGP 29JUN      1